packages:
  - apps/*
  - packages/*
  - packages/configs/*

catalog:
  "@tailwindcss/postcss": ^4.1.18
  "@types/node": ^25.0.3
  "@typescript-eslint/eslint-plugin": ^8.53.0
  "@typescript-eslint/parser": ^8.53.0
  autoprefixer: ^10.4.23
  eslint: ^9.19.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.0.0
  postcss: ^8.5.6
  prettier: ^3.5.1
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
